spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: jigar
    password: jwala
    
  jpa:
    show-sql: true
#    generate-ddl: true
    
    
   